//首页 type
export const REQUEST_HOME_LIST = 'REQUEST_HOME_LIST'
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST'
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST'

//banner
export const REQUEST_BANNER_LIST = 'REQUEST_BANNER_LIST'
export const FETCH_BANNER_LIST = 'FETCH_BANNER_LIST'
export const RECEIVE_BANNER_LIST = 'RECEIVE_BANNER_LIST'

//发现页面 type
export const REQUEST_COVER_LIST = 'REQUEST_COVER_LIST'
export const FETCH_COVER_LIST = 'FETCH_COVER_LIST'
export const RECEIVE_COVER_LIST = 'RECEIVE_COVER_LIST'

//发现页面详情 type
export const REQUEST_COVER_DETAIL = 'REQUEST_COVER_DETAIL'
export const FETCH_COVER_DETAIL = 'FETCH_COVER_DETAIL'
export const RECEIVE_COVER_DETAIL = 'RECEIVE_COVER_DETAIL'

//登录
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const FETCH_LOGIN = 'FETCH_LOGIN'
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN'
