export const REQUEST_HOME_LIST = 'REQUEST_HOME_LIST'
export const FETCH_HOME_LIST = 'FETCH_HOME_LIST'
export const RECEIVE_HOME_LIST = 'RECEIVE_HOME_LIST'

export const REQUEST_COVER_LIST = 'REQUEST_COVER_LIST'
export const FETCH_COVER_LIST = 'FETCH_COVER_LIST'
export const RECEIVE_COVER_LIST = 'RECEIVE_COVER_LIST'
