export const HOME_LIST = 'http://www.wanandroid.com/article/list'
export const COVER_LIST = 'http://www.wanandroid.com/tree/json'
export const FAVORITE_LIST = 'http://www.wanandroid.com/lg/collect/list/0/json'
export const BANNER_LIST = 'http://www.wanandroid.com/banner/json'
export const COVER_DETAIL = 'http://www.wanandroid.com/article/list'
export const LOGIN = 'http://www.wanandroid.com/user/login'
